[Journal]
Storage=persistent
Compress=yes

# Kh?ng cho journal chi?m qu? nhi?u SD card.
SystemMaxUse=200M
SystemKeepFree=500M
SystemMaxFileSize=25M

# Gi? log t?i ?a 14 ng?y.
MaxRetentionSec=14day

# M?t journal file kh?ng k?o d?i qu? 1 ng?y.
MaxFileSec=1day

# Ch?ng log storm.
RateLimitIntervalSec=30s
RateLimitBurst=10000
